name: Build and deploy ASP.NET Core app to Azure Web App - learningwebapp2668

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # adjust to your project version

      - name: Restore dependencies
        run: dotnet restore applearning/applearning.csproj

      - name: Build
        run: dotnet build applearning/applearning.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish applearning/applearning.csproj --configuration Release --output ./published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./published

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B27619DF419D4A59AF4C261C7495D3E0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4B1E09782F64F1AA987E5A3315125AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE2A5A3F9ECA4CCE96A1C1774EEA9DE7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'learningwebapp2668'
          slot-name: 'Production'
          package: ./published
